{% set version = "0.10.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-geojsonio
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/geojsonio_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/geojsonio/geojsonio_{{ version }}.tar.gz
  sha256: e2657ad73aeace7d98634763ea2950c2fbbefd745bc8d030cab4402facd453d1

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-v8
    - r-crul
    - r-geojson >=0.2.0
    - r-geojsonsf
    - r-jqr
    - r-jsonlite >=0.9.21
    - r-magrittr
    - r-maptools
    - r-readr >=0.2.2
    - r-rgeos
    - r-sf >=0.6
    - r-sp
  run:
    - r-base
    - r-v8
    - r-crul
    - r-geojson >=0.2.0
    - r-geojsonsf
    - r-jqr
    - r-jsonlite >=0.9.21
    - r-magrittr
    - r-maptools
    - r-readr >=0.2.2
    - r-rgeos
    - r-sf >=0.6
    - r-sp

test:
  commands:
    - $R -e "library('geojsonio')"           # [not win]
    - "\"%R%\" -e \"library('geojsonio')\""  # [win]

about:
  home: https://github.com/ropensci/geojsonio (devel), https://docs.ropensci.org/geojsonio (docs)
  license: MIT
  summary: Convert data to 'GeoJSON' or 'TopoJSON' from various R classes, including vectors, lists, data frames, shape files, and spatial classes. 'geojsonio' does not aim to replace packages like 'sp', 'rgdal', 'rgeos', but rather aims to be a high level client to simplify conversions of data from and to 'GeoJSON' and
    'TopoJSON'.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - xhochy

# Package: geojsonio
# Title: Convert Data from and to 'GeoJSON' or 'TopoJSON'
# Description: Convert data to 'GeoJSON' or 'TopoJSON' from various R classes, including vectors, lists, data frames, shape files, and spatial classes. 'geojsonio' does not aim to replace packages like 'sp', 'rgdal', 'rgeos', but rather aims to be a high level client to simplify conversions of data from and to 'GeoJSON' and 'TopoJSON'.
# Version: 0.9.0
# License: MIT + file LICENSE
# Authors@R: c( person("Scott", "Chamberlain", role = c("aut", "cre"), email = "myrmecocystus@gmail.com"), person("Andy", "Teucher", role = "aut", email = "andy.teucher@gmail.com") )
# URL: https://github.com/ropensci/geojsonio (devel), https://docs.ropensci.org/geojsonio (docs)
# BugReports: https://github.com/ropensci/geojsonio/issues
# LazyData: true
# VignetteBuilder: knitr
# Encoding: UTF-8
# Depends: R (>= 2.10)
# Imports: methods, sp, sf (>= 0.6), rgeos, crul, maptools, jsonlite (>= 0.9.21), magrittr, readr (>= 0.2.2), V8, geojson (>= 0.2.0), jqr
# Suggests: gistr, testthat, knitr, rmarkdown, leaflet, maps, DBI, RPostgres
# Enhances: RColorBrewer
# RoxygenNote: 7.0.2
# X-schema.org-applicationCategory: Geospatial
# X-schema.org-keywords: geojson, topojson, geospatial, conversion, data, input-output
# X-schema.org-isPartOf: https://ropensci.org
# NeedsCompilation: no
# Packaged: 2020-02-11 22:08:54 UTC; sckott
# Author: Scott Chamberlain [aut, cre], Andy Teucher [aut]
# Maintainer: Scott Chamberlain <myrmecocystus@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-02-13 09:30:05 UTC
