appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: KoJEZbYvSMyUK9BKJoAN7lovkf2QmyQ94UDXgCFzPxABpJZWYh+RF2jdxDx166iiNRLfs0h7B7XgH6lp99MctC49V0IpCY+jY7AlWz4UhQcIj+vnA6y7levq/CJFtp57tOl772gx+aS50nPimKokinQxAE20yQy8VYjfQ7yeGO54ZXcVj0bH7SLsHyiBYItQZdS+RZCkLpdLX+9F6ZeUt9EjDCJig5hVOZX33E+smhyh8hOexomPvU6y/f17fednEQGgDq4hzittMlNRjFIrW32+QqFbTYhCBQxjgNK3e6oJkcXpyA8wz76a+6BEMpWEe1y8pWY7dixnilfuPxL4Hc96LquLxKEs/xgjeic/VLKvVrg1cb9c8vdf7BMqVYB0SmGsV/iWLMWYwB48jSvuoXtt+pDODhqK2+CBR1Oz8z8PF9A0vFtcfZgxkn0ce9/0TEWyvyj0AC12JTMYykXqIoHLhL5KB044U/p/RZHlUTtGmhg5vHJUZJeZsMx6l6tdLodOy1KzXRwxpkPet5cR7jy8HkpyEEiHH2FQU89fjGBONIpxHfIJvOcKlmay84fyuacOOoPYI1TvSNZjBkYMN0WULE8ueaspkl5ahg5yuLhNdG0EZQSStlVn7o2CAXBfAjPfo6iPrM1X1VNFpsg/4700rCojznu9mCptibE3aAY=
